name: Release Templates PDF

on:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'beamer/**'
  #     - 'shared/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/xu-cheng/texlive-full:latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile Beamer PDF
      working-directory: ./beamer
      run: |
        latexmk -interaction=nonstopmode -file-line-error -pdfxe -shell-escape -jobname=beamer-template main.tex

    - name: Upload Beamer PDF
      uses: actions/upload-artifact@v4
      with:
        name: beamer-template.pdf
        path: ./beamer/beamer-template.pdf

    - name: Get timestamp
      id: timestamp
      run: echo "time=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        files: ./beamer/beamer-template.pdf
        tag_name: latex-templates-v${{ steps.timestamp.outputs.time }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
